# Generated by Django 6.0.5 on 2026-05-31 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('glucose', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('haemoglobin', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('cholesterol', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('remarks', models.TextField(blank=True, default='')),
            ],
        ),
    ]
